apiVersion: v2
name: temporal-worker-controller-crds
description: CRDs for the Temporal Worker Controller. Install this chart before the temporal-worker-controller chart.
type: application
version: 0.24.1
