version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 14

  - package-ecosystem: gomod
    directory: "/internal/demo"
    schedule:
      interval: weekly
    cooldown:
      default-days: 14

  - package-ecosystem: gomod
    directory: "/internal/tests"
    schedule:
      interval: weekly
    cooldown:
      default-days: 14

  - package-ecosystem: helm
    directory: "/helm/temporal-worker-controller"
    schedule:
      interval: weekly
    cooldown:
      default-days: 14

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 14
