apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: worker-controller
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
      ignoreChanges: true
profiles:
  # Build and deploy the controller to the local k8s cluster  
  - name: worker-controller
    build:
      tagPolicy:
        envTemplate:
          template: "latest"
      artifacts:
        - image: temporal-worker-controller
          context: .
          docker:
            dockerfile: Dockerfile
    manifests:
      helm:
        releases:
          - name: temporal-worker-controller
            chartPath: helm/temporal-worker-controller
            namespace: temporal-system
            createNamespace: true
            setValues:
              image.repository: temporal-worker-controller
              image.tag: latest
              image.pullPolicy: IfNotPresent
              namespace.create: true
            valuesFiles:
              - helm/temporal-worker-controller/values.yaml

  # Build and deploy the helloworld Custom Resource to the local k8s cluster  
  - name: helloworld-worker
    build:
      artifacts:
        - image: helloworld
          context: internal/demo
          docker:
            dockerfile: Dockerfile
            buildArgs:
              DD_GIT_COMMIT_SHA: "{{ .IMAGE_TAG }}"
              DD_GIT_REPOSITORY_URL: "github.com/temporalio/temporal-worker-controller"
              WORKER: "helloworld"
    manifests:
      helm:
        releases:
          - name: helloworld
            chartPath: internal/demo/helloworld/helm/helloworld
            setValueTemplates:
              image.repository: "{{ .IMAGE_REPO_helloworld }}"
              image.tag: "{{ .IMAGE_TAG_helloworld }}"
              # These connection settings are meant to be defined in skaffold.env (see skaffold.example.env)
              temporal.namespace: "{{ .TEMPORAL_NAMESPACE }}"
              temporal.address: "{{ .TEMPORAL_ADDRESS }}"
              temporal.mtlsSecretName: "{{ .TEMPORAL_MTLS_SECRET_NAME }}"
            valuesFiles:
              - internal/demo/helloworld/helm/helloworld/values.yaml
deploy:
  helm:
    hooks:
      before:
        - host:
            command: ["./internal/demo/scripts/update_chart_version.sh"]
      after:
        - host:
            command: ["sh", "-c", "sed -i '' 's/appVersion: .*/appVersion: \"automated\"/' internal/demo/helloworld/helm/helloworld/Chart.yaml"]
resourceSelector:
  allow:
    - groupKind: "TemporalWorkerDeployment.temporal.io"
      image: [".*"]
