apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: worker-controller
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
      ignoreChanges: true
profiles:
  # Build and deploy the controller to the local k8s cluster  
  - name: worker-controller
    build:
      tagPolicy:
        envTemplate:
          template: "latest"
      artifacts:
        - image: temporal-worker-controller
          context: .
          docker:
            dockerfile: Dockerfile
    manifests:
      helm:
        releases:
          - name: temporal-worker-controller
            chartPath: helm/temporal-worker-controller
            namespace: temporal-worker-controller
            createNamespace: true
            setValues:
              image.repository: temporal-worker-controller
              image.tag: latest
              image.pullPolicy: IfNotPresent
              namespace.create: true
            valuesFiles:
              - helm/temporal-worker-controller/values.yaml

  # Build and deploy the helloworld Custom Resource to the local k8s cluster  
  - name: helloworld-worker
    build:
      artifacts:
        - image: helloworld
          context: internal/demo
          docker:
            dockerfile: Dockerfile
            buildArgs:
              DD_GIT_COMMIT_SHA: "{{ .IMAGE_TAG }}"
              DD_GIT_REPOSITORY_URL: "github.com/temporalio/temporal-worker-controller"
              WORKER: "helloworld"
    manifests:
      rawYaml:
        - internal/demo/helloworld/temporal_worker_deployment.yaml
deploy:
  kubeContext: minikube
  kubectl: {}
resourceSelector:
  allow:
    - groupKind: "TemporalWorkerDeployment.temporal.io"
      image: [".*"]
