---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-temporal-io-temporal-io-v1alpha1-temporalworkerdeployment
  failurePolicy: Fail
  name: mtemporalworker.kb.io
  rules:
  - apiGroups:
    - temporal.io.temporal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - temporalworkers
  sideEffects: None
