---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/scale
  verbs:
  - update
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - temporal.io
  resources:
  - connections
  - temporalconnections
  - workerresourcetemplates
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - temporal.io
  resources:
  - connections/finalizers
  - temporalconnections/finalizers
  - temporalworkerdeployments/finalizers
  - workerdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - temporal.io
  resources:
  - temporalconnections/status
  - temporalworkerdeployments/status
  - workerdeployments/status
  - workerresourcetemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - temporal.io
  resources:
  - temporalworkerdeployments
  - workerdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
