// Command helm-values-schema generates values.schema.json from values.yaml.
// By default, each key's type comes from its default value and its description
// from the comment above it. Constraints that cannot be inferred (enums,
// patterns, item shape) are added with "# @schema" comments on the key, e.g.:
//
//	pullPolicy: IfNotPresent # @schema enum:[Always, IfNotPresent, Never]
//	port: 8080               # @schema minimum:1; maximum:65535
//	extraEnv: []             # @schema items.type:object; items.required:[name]
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	valuesRel = "helm/temporal-worker-controller/values.yaml"
	schemaRel = "helm/temporal-worker-controller/values.schema.json"

	schemaComment = "Generated from helm/temporal-worker-controller/values.yaml by make helm-values-schema. Do not edit this file by hand."
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "helm-values-schema: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := repoRoot()
	if err != nil {
		return err
	}

	raw, err := os.ReadFile(filepath.Join(root, valuesRel))
	if err != nil {
		return err
	}

	var doc yaml.Node
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		return fmt.Errorf("parse %s: %w", valuesRel, err)
	}
	if len(doc.Content) == 0 {
		return fmt.Errorf("%s is empty", valuesRel)
	}

	generated := schemaFromNode(doc.Content[0])
	if generated == nil {
		return fmt.Errorf("failed to infer schema from %s", valuesRel)
	}
	generated["$schema"] = "https://json-schema.org/draft-07/schema#"
	generated["$comment"] = schemaComment
	generated["required"] = []any{}

	out, err := json.MarshalIndent(generated, "", "  ")
	if err != nil {
		return err
	}
	out = append(out, '\n')

	dest := filepath.Join(root, schemaRel)
	if err := os.WriteFile(dest, out, 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s\n", schemaRel)
	return nil
}

func repoRoot() (string, error) {
	out, err := exec.Command("git", "rev-parse", "--show-toplevel").Output()
	if err != nil {
		return "", fmt.Errorf("find repo root: %w", err)
	}
	return strings.TrimSpace(string(out)), nil
}

func schemaFromNode(n *yaml.Node) map[string]any {
	if n == nil {
		return map[string]any{"type": "object"}
	}
	switch n.Kind {
	case yaml.DocumentNode:
		if len(n.Content) == 0 {
			return map[string]any{"type": "object"}
		}
		return schemaFromNode(n.Content[0])
	case yaml.MappingNode:
		s := map[string]any{"type": "object"}
		if len(n.Content) == 0 {
			return s
		}
		props := map[string]any{}
		for i := 0; i+1 < len(n.Content); i += 2 {
			key := n.Content[i]
			val := n.Content[i+1]
			prop := schemaFromNode(val)
			if desc := commentDescription(key, val); desc != "" {
				prop["description"] = desc
			}
			if ann := schemaDirectives(key.HeadComment, key.LineComment, val.HeadComment, val.LineComment); len(ann) > 0 {
				if merged, ok := asMap(deepMerge(prop, ann)); ok {
					prop = merged
				}
			}
			props[key.Value] = prop
		}
		s["properties"] = props
		return s
	case yaml.SequenceNode:
		s := map[string]any{"type": "array"}
		if len(n.Content) > 0 {
			s["items"] = schemaFromNode(n.Content[0])
		}
		return s
	case yaml.ScalarNode:
		return map[string]any{"type": scalarType(n)}
	default:
		return map[string]any{"type": "object"}
	}
}

func scalarType(n *yaml.Node) any {
	switch n.Tag {
	case "!!bool":
		return "boolean"
	case "!!int":
		return "integer"
	case "!!float":
		return "number"
	case "!!null":
		return []any{"string", "null"}
	default:
		if n.Value == "true" || n.Value == "false" {
			return "boolean"
		}
		if _, err := strconv.ParseInt(n.Value, 10, 64); err == nil && n.Style != yaml.SingleQuotedStyle && n.Style != yaml.DoubleQuotedStyle {
			return "integer"
		}
		return "string"
	}
}

func commentDescription(key, val *yaml.Node) string {
	parts := []string{
		cleanComment(key.HeadComment),
		cleanComment(key.LineComment),
		cleanComment(val.HeadComment),
		cleanComment(val.LineComment),
	}
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		if b.Len() > 0 {
			b.WriteString("\n")
		}
		b.WriteString(p)
	}
	return b.String()
}

func cleanComment(c string) string {
	if c == "" {
		return ""
	}
	var lines []string
	for _, line := range strings.Split(c, "\n") {
		line = strings.TrimRight(line, " \t")
		line = strings.TrimSpace(line)
		line = strings.TrimPrefix(line, "#")
		if strings.HasPrefix(line, " ") {
			line = line[1:]
		}
		if i := strings.Index(line, "@schema"); i >= 0 {
			line = strings.TrimSpace(line[:i])
		}
		if line == "" {
			if len(lines) > 0 && lines[len(lines)-1] != "" {
				lines = append(lines, "")
			}
			continue
		}
		lines = append(lines, line)
	}
	return strings.TrimSpace(strings.Join(lines, "\n"))
}

// schemaDirectives reads Traefik-style "# @schema" comments. Directives on one
// line are separated by semicolons. Dotted keys set nested schema fields, for
// example "items.required:[name]".
func schemaDirectives(comments ...string) map[string]any {
	out := map[string]any{}
	for _, c := range comments {
		for _, line := range strings.Split(c, "\n") {
			line = strings.TrimSpace(line)
			line = strings.TrimPrefix(line, "#")
			line = strings.TrimSpace(line)
			idx := strings.Index(line, "@schema")
			if idx < 0 {
				continue
			}
			for _, dir := range splitDirectives(strings.TrimSpace(line[idx+len("@schema"):])) {
				key, raw, ok := strings.Cut(dir, ":")
				key = strings.TrimSpace(key)
				if !ok || key == "" {
					continue
				}
				setPath(out, key, parseSchemaValue(strings.TrimSpace(raw)))
			}
		}
	}
	return out
}

func splitDirectives(s string) []string {
	var parts []string
	var b strings.Builder
	depth := 0
	for _, r := range s {
		switch r {
		case '[':
			depth++
			b.WriteRune(r)
		case ']':
			if depth > 0 {
				depth--
			}
			b.WriteRune(r)
		case ';':
			if depth == 0 {
				if p := strings.TrimSpace(b.String()); p != "" {
					parts = append(parts, p)
				}
				b.Reset()
				continue
			}
			b.WriteRune(r)
		default:
			b.WriteRune(r)
		}
	}
	if p := strings.TrimSpace(b.String()); p != "" {
		parts = append(parts, p)
	}
	return parts
}

func parseSchemaValue(raw string) any {
	if strings.HasPrefix(raw, "[") && strings.HasSuffix(raw, "]") {
		inner := strings.TrimSpace(raw[1 : len(raw)-1])
		if inner == "" {
			return []any{}
		}
		var items []any
		for _, part := range strings.Split(inner, ",") {
			part = strings.TrimSpace(part)
			part = strings.Trim(part, `"'`)
			if part == "" {
				continue
			}
			items = append(items, part)
		}
		return items
	}
	if n, err := strconv.ParseInt(raw, 10, 64); err == nil {
		return n
	}
	return strings.Trim(raw, `"'`)
}

func setPath(dst map[string]any, path string, value any) {
	parts := strings.Split(path, ".")
	cur := dst
	for i, part := range parts {
		if i == len(parts)-1 {
			cur[part] = value
			return
		}
		next, ok := cur[part].(map[string]any)
		if !ok {
			next = map[string]any{}
			cur[part] = next
		}
		cur = next
	}
}

func deepMerge(base, overlay any) any {
	bm, bok := asMap(base)
	om, ook := asMap(overlay)
	if !bok || !ook {
		if overlay == nil {
			return base
		}
		return overlay
	}
	out := make(map[string]any, len(bm)+len(om))
	for k, v := range bm {
		out[k] = v
	}
	for k, v := range om {
		if existing, ok := out[k]; ok {
			out[k] = deepMerge(existing, v)
		} else {
			out[k] = v
		}
	}
	return out
}

func asMap(v any) (map[string]any, bool) {
	switch m := v.(type) {
	case map[string]any:
		return m, true
	case map[any]any:
		out := make(map[string]any, len(m))
		for k, val := range m {
			out[fmt.Sprint(k)] = val
		}
		return out, true
	default:
		return nil, false
	}
}
