// Unless explicitly stated otherwise all files in this repository are licensed under the MIT License.
//
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2024 Datadog, Inc.

package v1alpha1_test

import (
	"context"
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	temporaliov1alpha1 "github.com/temporalio/temporal-worker-controller/api/v1alpha1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// newTWOR builds a TemporalWorkerOwnedResource with an arbitrary embedded object spec.
func newTWOR(name, temporalWorkerDeploymentRefName string, embeddedObj map[string]interface{}) *temporaliov1alpha1.TemporalWorkerOwnedResource {
	raw, _ := json.Marshal(embeddedObj)
	return &temporaliov1alpha1.TemporalWorkerOwnedResource{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: "default",
		},
		Spec: temporaliov1alpha1.TemporalWorkerOwnedResourceSpec{
			TemporalWorkerDeploymentRef: temporaliov1alpha1.TemporalWorkerDeploymentReference{
				Name: temporalWorkerDeploymentRefName,
			},
			Object: runtime.RawExtension{Raw: raw},
		},
	}
}

// validHPAObject returns a minimal valid HPA embedded object spec.
func validHPAObject() map[string]interface{} {
	return map[string]interface{}{
		"apiVersion": "autoscaling/v2",
		"kind":       "HorizontalPodAutoscaler",
		"spec": map[string]interface{}{
			"minReplicas": float64(2),
			"maxReplicas": float64(10),
		},
	}
}

// newValidatorNoAPI creates a validator with no API client (API checks skipped).
func newValidatorNoAPI() *temporaliov1alpha1.TemporalWorkerOwnedResourceValidator {
	return &temporaliov1alpha1.TemporalWorkerOwnedResourceValidator{
		BannedKinds: []string{"Deployment", "StatefulSet", "Job", "Pod", "CronJob"},
	}
}

func TestTemporalWorkerOwnedResource_ValidateCreate(t *testing.T) {
	tests := map[string]struct {
		obj      runtime.Object
		errorMsg string
	}{
		"valid HPA": {
			obj: newTWOR("my-hpa", "my-worker", validHPAObject()),
		},
		"wrong object type": {
			obj:      &corev1.Pod{ObjectMeta: metav1.ObjectMeta{Name: "pod"}},
			errorMsg: "expected a TemporalWorkerOwnedResource",
		},
		"nil raw object": {
			obj: &temporaliov1alpha1.TemporalWorkerOwnedResource{
				ObjectMeta: metav1.ObjectMeta{Name: "empty", Namespace: "default"},
				Spec: temporaliov1alpha1.TemporalWorkerOwnedResourceSpec{
					TemporalWorkerDeploymentRef: temporaliov1alpha1.TemporalWorkerDeploymentReference{Name: "my-worker"},
					Object:                      runtime.RawExtension{Raw: nil},
				},
			},
			errorMsg: "object must be specified",
		},
		"missing apiVersion": {
			obj: newTWOR("no-apiv", "my-worker", map[string]interface{}{
				"kind": "HorizontalPodAutoscaler",
				"spec": map[string]interface{}{"minReplicas": float64(1)},
			}),
			errorMsg: "apiVersion must be specified",
		},
		"missing kind": {
			obj: newTWOR("no-kind", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"spec":       map[string]interface{}{"minReplicas": float64(1)},
			}),
			errorMsg: "kind must be specified",
		},
		"metadata.name set in embedded object": {
			obj: newTWOR("has-name", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"kind":       "HorizontalPodAutoscaler",
				"metadata":   map[string]interface{}{"name": "fixed-name"},
				"spec":       map[string]interface{}{"minReplicas": float64(2)},
			}),
			errorMsg: "metadata.name is generated by the controller",
		},
		"metadata.namespace set in embedded object": {
			obj: newTWOR("has-ns", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"kind":       "HorizontalPodAutoscaler",
				"metadata":   map[string]interface{}{"namespace": "some-ns"},
				"spec":       map[string]interface{}{"minReplicas": float64(2)},
			}),
			errorMsg: "metadata.namespace is set by the controller",
		},
		"banned kind Deployment": {
			obj: newTWOR("bad-deploy", "my-worker", map[string]interface{}{
				"apiVersion": "apps/v1",
				"kind":       "Deployment",
				"spec":       map[string]interface{}{},
			}),
			errorMsg: `kind "Deployment" is not allowed`,
		},
		"banned kind StatefulSet": {
			obj: newTWOR("bad-sts", "my-worker", map[string]interface{}{
				"apiVersion": "apps/v1",
				"kind":       "StatefulSet",
				"spec":       map[string]interface{}{},
			}),
			errorMsg: `kind "StatefulSet" is not allowed`,
		},
		"banned kind Pod": {
			obj: newTWOR("bad-pod", "my-worker", map[string]interface{}{
				"apiVersion": "v1",
				"kind":       "Pod",
				"spec":       map[string]interface{}{},
			}),
			errorMsg: `kind "Pod" is not allowed`,
		},
		"banned kind case-insensitive": {
			obj: newTWOR("bad-job", "my-worker", map[string]interface{}{
				"apiVersion": "batch/v1",
				"kind":       "job", // lowercase
				"spec":       map[string]interface{}{},
			}),
			errorMsg: `kind "job" is not allowed`,
		},
		"minReplicas is 0": {
			obj: newTWOR("zero-replicas", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"kind":       "HorizontalPodAutoscaler",
				"spec": map[string]interface{}{
					"minReplicas": float64(0),
					"maxReplicas": float64(5),
				},
			}),
			errorMsg: "minReplicas must not be 0",
		},
		"non-null scaleTargetRef": {
			obj: newTWOR("has-scale-ref", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"kind":       "HorizontalPodAutoscaler",
				"spec": map[string]interface{}{
					"scaleTargetRef": map[string]interface{}{
						"apiVersion": "apps/v1",
						"kind":       "Deployment",
						"name":       "some-other-deployment",
					},
					"minReplicas": float64(2),
					"maxReplicas": float64(10),
				},
			}),
			errorMsg: "if scaleTargetRef is present, the controller owns it",
		},
		"null scaleTargetRef is valid (opt-in)": {
			obj: newTWOR("null-scale-ref", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"kind":       "HorizontalPodAutoscaler",
				"spec": map[string]interface{}{
					"scaleTargetRef": nil, // null = opt-in sentinel
					"minReplicas":    float64(2),
					"maxReplicas":    float64(10),
				},
			}),
		},
		"non-null selector.matchLabels": {
			obj: newTWOR("has-match-labels", "my-worker", map[string]interface{}{
				"apiVersion": "policy/v1",
				"kind":       "PodDisruptionBudget",
				"spec": map[string]interface{}{
					"minAvailable": float64(1),
					"selector": map[string]interface{}{
						"matchLabels": map[string]interface{}{
							"app": "my-worker",
						},
					},
				},
			}),
			errorMsg: "if selector.matchLabels is present, the controller owns it",
		},
		"null selector.matchLabels is valid (opt-in)": {
			obj: newTWOR("null-match-labels", "my-worker", map[string]interface{}{
				"apiVersion": "policy/v1",
				"kind":       "PodDisruptionBudget",
				"spec": map[string]interface{}{
					"minAvailable": float64(1),
					"selector": map[string]interface{}{
						"matchLabels": nil, // null = opt-in sentinel
					},
				},
			}),
		},
		"absent selector.matchLabels is valid": {
			obj: newTWOR("no-match-labels", "my-worker", map[string]interface{}{
				"apiVersion": "policy/v1",
				"kind":       "PodDisruptionBudget",
				"spec": map[string]interface{}{
					"minAvailable": float64(1),
					"selector":     map[string]interface{}{},
				},
			}),
		},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			ctx := context.Background()
			v := newValidatorNoAPI()

			warnings, err := v.ValidateCreate(ctx, tc.obj)

			if tc.errorMsg != "" {
				require.Error(t, err, "expected an error containing %q", tc.errorMsg)
				assert.Contains(t, err.Error(), tc.errorMsg)
			} else {
				require.NoError(t, err)
			}
			assert.Nil(t, warnings)
		})
	}
}

func TestTemporalWorkerOwnedResource_ValidateUpdate_Immutability(t *testing.T) {
	tests := map[string]struct {
		oldTemporalWorkerDeploymentRef string
		newTemporalWorkerDeploymentRef string
		errorMsg                       string
	}{
		"same temporalWorkerDeploymentRef is valid": {
			oldTemporalWorkerDeploymentRef: "my-worker",
			newTemporalWorkerDeploymentRef: "my-worker",
		},
		"changing temporalWorkerDeploymentRef is forbidden": {
			oldTemporalWorkerDeploymentRef: "my-worker",
			newTemporalWorkerDeploymentRef: "different-worker",
			errorMsg:                       "temporalWorkerDeploymentRef.name is immutable",
		},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			ctx := context.Background()
			v := newValidatorNoAPI()

			oldTWOR := newTWOR("my-hpa", tc.oldTemporalWorkerDeploymentRef, validHPAObject())
			newTWOR := newTWOR("my-hpa", tc.newTemporalWorkerDeploymentRef, validHPAObject())

			_, err := v.ValidateUpdate(ctx, oldTWOR, newTWOR)

			if tc.errorMsg != "" {
				require.Error(t, err)
				assert.Contains(t, err.Error(), tc.errorMsg)
			} else {
				require.NoError(t, err)
			}
		})
	}
}

func TestTemporalWorkerOwnedResource_ValidateUpdate_ValidatesNewSpec(t *testing.T) {
	ctx := context.Background()
	v := newValidatorNoAPI()

	// Update from a valid spec to one with banned kind should fail
	oldTWOR := newTWOR("my-hpa", "my-worker", validHPAObject())
	invalidNew := newTWOR("my-hpa", "my-worker", map[string]interface{}{
		"apiVersion": "apps/v1",
		"kind":       "Deployment",
		"spec":       map[string]interface{}{},
	})

	_, err := v.ValidateUpdate(ctx, oldTWOR, invalidNew)
	require.Error(t, err)
	assert.Contains(t, err.Error(), `kind "Deployment" is not allowed`)
}

func TestTemporalWorkerOwnedResource_ValidateDelete(t *testing.T) {
	ctx := context.Background()
	v := newValidatorNoAPI()

	// When API client is nil, delete permission checks are skipped
	twor := newTWOR("my-hpa", "my-worker", validHPAObject())
	warnings, err := v.ValidateDelete(ctx, twor)
	assert.NoError(t, err)
	assert.Nil(t, warnings)
}

func TestTemporalWorkerOwnedResource_ValidateDelete_WrongObjectType(t *testing.T) {
	ctx := context.Background()
	v := newValidatorNoAPI()

	_, err := v.ValidateDelete(ctx, &corev1.Pod{})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "expected a TemporalWorkerOwnedResource")
}

func TestTemporalWorkerOwnedResource_ValidateDelete_NilRaw(t *testing.T) {
	ctx := context.Background()
	v := newValidatorNoAPI()

	// TWOR with nil spec.object should be permitted (nothing to check)
	twor := &temporaliov1alpha1.TemporalWorkerOwnedResource{
		ObjectMeta: metav1.ObjectMeta{Name: "empty", Namespace: "default"},
		Spec: temporaliov1alpha1.TemporalWorkerOwnedResourceSpec{
			TemporalWorkerDeploymentRef: temporaliov1alpha1.TemporalWorkerDeploymentReference{Name: "my-worker"},
			Object:                      runtime.RawExtension{Raw: nil},
		},
	}
	_, err := v.ValidateDelete(ctx, twor)
	assert.NoError(t, err)
}

func TestTemporalWorkerOwnedResource_ValidateCreate_WrongObjectType(t *testing.T) {
	ctx := context.Background()
	v := newValidatorNoAPI()

	_, err := v.ValidateCreate(ctx, &corev1.Pod{})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "expected a TemporalWorkerOwnedResource")
}

func TestTemporalWorkerOwnedResource_ValidateUpdate_WrongObjectType(t *testing.T) {
	ctx := context.Background()
	v := newValidatorNoAPI()

	_, err := v.ValidateUpdate(ctx, &corev1.Pod{}, newTWOR("x", "w", validHPAObject()))
	require.Error(t, err)
	assert.Contains(t, err.Error(), "expected a TemporalWorkerOwnedResource for old object")

	_, err = v.ValidateUpdate(ctx, newTWOR("x", "w", validHPAObject()), &corev1.Pod{})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "expected a TemporalWorkerOwnedResource for new object")
}

func TestTemporalWorkerOwnedResource_CustomBannedKinds(t *testing.T) {
	ctx := context.Background()
	v := &temporaliov1alpha1.TemporalWorkerOwnedResourceValidator{
		BannedKinds: []string{"CustomBannedKind"},
	}

	// CustomBannedKind should be rejected
	_, err := v.ValidateCreate(ctx, newTWOR("bad", "my-worker", map[string]interface{}{
		"apiVersion": "example.com/v1",
		"kind":       "CustomBannedKind",
		"spec":       map[string]interface{}{},
	}))
	require.Error(t, err)
	assert.Contains(t, err.Error(), `kind "CustomBannedKind" is not allowed`)

	// Default banned kinds (Deployment) should be allowed if custom list is set
	_, err = v.ValidateCreate(ctx, newTWOR("deploy", "my-worker", map[string]interface{}{
		"apiVersion": "apps/v1",
		"kind":       "Deployment",
		"spec":       map[string]interface{}{},
	}))
	require.NoError(t, err, "Deployment should be allowed when custom bannedKinds list does not include it")
}

func TestTemporalWorkerOwnedResource_MultipleErrors(t *testing.T) {
	ctx := context.Background()
	v := newValidatorNoAPI()

	// Both metadata.name and minReplicas=0 are invalid
	obj := map[string]interface{}{
		"apiVersion": "autoscaling/v2",
		"kind":       "HorizontalPodAutoscaler",
		"metadata":   map[string]interface{}{"name": "bad-name"},
		"spec": map[string]interface{}{
			"minReplicas": float64(0),
			"maxReplicas": float64(5),
		},
	}
	_, err := v.ValidateCreate(ctx, newTWOR("multi-err", "my-worker", obj))
	require.Error(t, err)
	assert.Contains(t, err.Error(), "metadata.name is generated by the controller")
	assert.Contains(t, err.Error(), "minReplicas must not be 0")
}
