// Unless explicitly stated otherwise all files in this repository are licensed under the MIT License.
//
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2024 Datadog, Inc.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// WorkerDeploymentReference references a TemporalWorkerDeployment in the same namespace.
type WorkerDeploymentReference struct {
	// Name of the TemporalWorkerDeployment resource in the same namespace.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Pattern=`^[a-z0-9]([-a-z0-9]*[a-z0-9])?$`
	Name string `json:"name"`
}

// TemporalWorkerOwnedResourceSpec defines the desired state of TemporalWorkerOwnedResource.
type TemporalWorkerOwnedResourceSpec struct {
	// WorkerRef references the TemporalWorkerDeployment to attach this resource to.
	// +kubebuilder:validation:Required
	WorkerRef WorkerDeploymentReference `json:"workerRef"`

	// Object is the Kubernetes resource template to attach to each versioned Deployment.
	// One copy of this resource is created per active Build ID, owned by the corresponding
	// versioned Deployment (so it is garbage collected when the Deployment is deleted).
	//
	// The object must include apiVersion, kind, and spec. The metadata.name and
	// metadata.namespace are generated by the controller and must not be set by the user.
	//
	// String values in the spec may contain Go template expressions:
	//   {{ .DeploymentName }}    - the controller-generated versioned Deployment name
	//   {{ .TemporalNamespace }} - the Temporal namespace the worker connects to
	//   {{ .BuildID }}           - the Build ID for this version
	//
	// The controller also auto-injects two well-known fields. If your resource requires these fields,
	// you must include them in the spec.object but leave them empty for the controller to fill in:
	//   scaleTargetRef - set to point at the versioned Deployment (for HPA, KEDA, WPA, etc.)
	//   matchLabels    - set to the versioned Deployment's selector labels (for PDB, WPA, etc.)
	// +kubebuilder:validation:Required
	// +kubebuilder:pruning:PreserveUnknownFields
	Object runtime.RawExtension `json:"object"`
}

// OwnedResourceVersionStatus describes the status of an owned resource for a single Build ID.
type OwnedResourceVersionStatus struct {
	// BuildID is the Build ID of the versioned Deployment this status entry refers to.
	BuildID string `json:"buildID"`

	// Applied is true if the resource was successfully applied for this Build ID.
	Applied bool `json:"applied"`

	// ResourceName is the name of the applied Kubernetes resource.
	// +optional
	ResourceName string `json:"resourceName,omitempty"`

	// Message describes any error if Applied is false.
	// +optional
	Message string `json:"message,omitempty"`

	// LastTransitionTime is the last time this status entry was updated.
	LastTransitionTime metav1.Time `json:"lastTransitionTime"`
}

// TemporalWorkerOwnedResourceStatus defines the observed state of TemporalWorkerOwnedResource.
type TemporalWorkerOwnedResourceStatus struct {
	// Versions describes the per-Build-ID status of owned resources.
	// +optional
	Versions []OwnedResourceVersionStatus `json:"versions,omitempty"`
}

//+kubebuilder:object:root=true
//+kubebuilder:subresource:status
//+kubebuilder:resource:shortName=twor
//+kubebuilder:printcolumn:name="Worker",type="string",JSONPath=".spec.workerRef.name",description="Referenced TemporalWorkerDeployment"
//+kubebuilder:printcolumn:name="Kind",type="string",JSONPath=".spec.object.kind",description="Kind of owned resource"
//+kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",description="Age"

// TemporalWorkerOwnedResource attaches an arbitrary namespaced Kubernetes resource
// (HPA, PDB, WPA, custom CRDs, etc.) to each per-Build-ID versioned Deployment
// managed by a TemporalWorkerDeployment. One copy of the resource is created per
// active Build ID and is owned by the corresponding versioned Deployment.
type TemporalWorkerOwnedResource struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   TemporalWorkerOwnedResourceSpec   `json:"spec,omitempty"`
	Status TemporalWorkerOwnedResourceStatus `json:"status,omitempty"`
}

//+kubebuilder:object:root=true

// TemporalWorkerOwnedResourceList contains a list of TemporalWorkerOwnedResource.
type TemporalWorkerOwnedResourceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TemporalWorkerOwnedResource `json:"items"`
}

func init() {
	SchemeBuilder.Register(&TemporalWorkerOwnedResource{}, &TemporalWorkerOwnedResourceList{})
}
