package v1alpha1_test

import (
	"context"
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	temporaliov1alpha1 "github.com/temporalio/temporal-worker-controller/api/v1alpha1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
)

// newWRT builds a WorkerResourceTemplate with an arbitrary embedded object spec.
func newWRT(name, temporalWorkerDeploymentRefName string, embeddedObj map[string]interface{}) *temporaliov1alpha1.WorkerResourceTemplate {
	raw, _ := json.Marshal(embeddedObj)
	return &temporaliov1alpha1.WorkerResourceTemplate{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: "default",
		},
		Spec: temporaliov1alpha1.WorkerResourceTemplateSpec{
			TemporalWorkerDeploymentRef: temporaliov1alpha1.TemporalWorkerDeploymentReference{
				Name: temporalWorkerDeploymentRefName,
			},
			Template: runtime.RawExtension{Raw: raw},
		},
	}
}

// validHPAObject returns a minimal valid HPA embedded object spec.
func validHPAObject() map[string]interface{} {
	return map[string]interface{}{
		"apiVersion": "autoscaling/v2",
		"kind":       "HorizontalPodAutoscaler",
		"spec": map[string]interface{}{
			"minReplicas": float64(2),
			"maxReplicas": float64(10),
		},
	}
}

// namespacedScope implements meta.RESTScope for namespace-scoped resources.
type namespacedScope struct{}

func (namespacedScope) Name() meta.RESTScopeName { return meta.RESTScopeNameNamespace }

// newFakeRESTMapper returns a DefaultRESTMapper with the given GroupVersionKinds registered as namespace-scoped.
func newFakeRESTMapper(gvks ...schema.GroupVersionKind) meta.RESTMapper {
	mapper := meta.NewDefaultRESTMapper(nil)
	for _, gvk := range gvks {
		mapper.Add(gvk, namespacedScope{})
	}
	return mapper
}

// newValidatorNoAPI creates a validator with a fake API client and a fake RESTMapper that
// recognises HPA (autoscaling/v2) and PDB (policy/v1) as namespace-scoped resources.
// AllowedKinds mirrors the default Helm values (HPA + PDB) so that most tests use realistic
// allowed kinds while kinds like Deployment remain disallowed.
// No admission request is present in unit-test contexts, so SubjectAccessReview calls are never
// reached; only the RESTMapper namespace-scope check exercises the fake mapper.
// Note: SubjectAccessReview calls are tested in workerresourcetemplate_webhook_integration_test.go.
func newValidatorNoAPI() *temporaliov1alpha1.WorkerResourceTemplateValidator {
	return &temporaliov1alpha1.WorkerResourceTemplateValidator{
		Client: fake.NewClientBuilder().Build(),
		RESTMapper: newFakeRESTMapper(
			schema.GroupVersionKind{Group: "autoscaling", Version: "v2", Kind: "HorizontalPodAutoscaler"},
			schema.GroupVersionKind{Group: "policy", Version: "v1", Kind: "PodDisruptionBudget"},
		),
		AllowedKinds: []string{"HorizontalPodAutoscaler", "PodDisruptionBudget"},
	}
}

func TestWorkerResourceTemplate_ValidateCreate(t *testing.T) {
	tests := map[string]struct {
		obj      runtime.Object
		errorMsg string
	}{
		"valid HPA": {
			obj: newWRT("my-hpa", "my-worker", validHPAObject()),
		},
		"wrong object type": {
			obj:      &corev1.Pod{ObjectMeta: metav1.ObjectMeta{Name: "pod"}},
			errorMsg: "expected a WorkerResourceTemplate",
		},
		"nil raw object": {
			obj: &temporaliov1alpha1.WorkerResourceTemplate{
				ObjectMeta: metav1.ObjectMeta{Name: "empty", Namespace: "default"},
				Spec: temporaliov1alpha1.WorkerResourceTemplateSpec{
					TemporalWorkerDeploymentRef: temporaliov1alpha1.TemporalWorkerDeploymentReference{Name: "my-worker"},
					Template:                    runtime.RawExtension{Raw: nil},
				},
			},
			errorMsg: "template must be specified",
		},
		"missing apiVersion": {
			obj: newWRT("no-apiv", "my-worker", map[string]interface{}{
				"kind": "HorizontalPodAutoscaler",
				"spec": map[string]interface{}{"minReplicas": float64(1)},
			}),
			errorMsg: "apiVersion must be specified",
		},
		"missing kind": {
			obj: newWRT("no-kind", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"spec":       map[string]interface{}{"minReplicas": float64(1)},
			}),
			errorMsg: "kind must be specified",
		},
		"metadata.name set in embedded object": {
			obj: newWRT("has-name", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"kind":       "HorizontalPodAutoscaler",
				"metadata":   map[string]interface{}{"name": "fixed-name"},
				"spec":       map[string]interface{}{"minReplicas": float64(2)},
			}),
			errorMsg: "metadata.name is generated by the controller",
		},
		"metadata.namespace set in embedded object": {
			obj: newWRT("has-ns", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"kind":       "HorizontalPodAutoscaler",
				"metadata":   map[string]interface{}{"namespace": "some-ns"},
				"spec":       map[string]interface{}{"minReplicas": float64(2)},
			}),
			errorMsg: "metadata.namespace is set by the controller",
		},
		"kind not in allowed list — Deployment": {
			obj: newWRT("bad-deploy", "my-worker", map[string]interface{}{
				"apiVersion": "apps/v1",
				"kind":       "Deployment",
				"spec":       map[string]interface{}{},
			}),
			errorMsg: `kind "Deployment" is not in the allowed list`,
		},
		"kind not in allowed list — StatefulSet": {
			obj: newWRT("bad-sts", "my-worker", map[string]interface{}{
				"apiVersion": "apps/v1",
				"kind":       "StatefulSet",
				"spec":       map[string]interface{}{},
			}),
			errorMsg: `kind "StatefulSet" is not in the allowed list`,
		},
		"kind not in allowed list — Pod": {
			obj: newWRT("bad-pod", "my-worker", map[string]interface{}{
				"apiVersion": "v1",
				"kind":       "Pod",
				"spec":       map[string]interface{}{},
			}),
			errorMsg: `kind "Pod" is not in the allowed list`,
		},
		"allowed kind check is case-insensitive": {
			obj: newWRT("bad-job", "my-worker", map[string]interface{}{
				"apiVersion": "batch/v1",
				"kind":       "job", // lowercase — not in allowed list
				"spec":       map[string]interface{}{},
			}),
			errorMsg: `kind "job" is not in the allowed list`,
		},
		"minReplicas is 0": {
			obj: newWRT("zero-replicas", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"kind":       "HorizontalPodAutoscaler",
				"spec": map[string]interface{}{
					"minReplicas": float64(0),
					"maxReplicas": float64(5),
				},
			}),
			errorMsg: "minReplicas must not be 0",
		},
		"non-null scaleTargetRef": {
			obj: newWRT("has-scale-ref", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"kind":       "HorizontalPodAutoscaler",
				"spec": map[string]interface{}{
					"scaleTargetRef": map[string]interface{}{
						"apiVersion": "apps/v1",
						"kind":       "Deployment",
						"name":       "some-other-deployment",
					},
					"minReplicas": float64(2),
					"maxReplicas": float64(10),
				},
			}),
			errorMsg: "if scaleTargetRef is present, the controller owns it",
		},
		"empty scaleTargetRef is valid (opt-in)": {
			obj: newWRT("empty-scale-ref", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"kind":       "HorizontalPodAutoscaler",
				"spec": map[string]interface{}{
					"scaleTargetRef": map[string]interface{}{}, // {} = opt-in sentinel
					"minReplicas":    float64(2),
					"maxReplicas":    float64(10),
				},
			}),
		},
		"non-null selector.matchLabels": {
			obj: newWRT("has-match-labels", "my-worker", map[string]interface{}{
				"apiVersion": "policy/v1",
				"kind":       "PodDisruptionBudget",
				"spec": map[string]interface{}{
					"minAvailable": float64(1),
					"selector": map[string]interface{}{
						"matchLabels": map[string]interface{}{
							"app": "my-worker",
						},
					},
				},
			}),
			errorMsg: "if selector.matchLabels is present, the controller owns it",
		},
		"empty selector.matchLabels is valid (opt-in)": {
			obj: newWRT("empty-match-labels", "my-worker", map[string]interface{}{
				"apiVersion": "policy/v1",
				"kind":       "PodDisruptionBudget",
				"spec": map[string]interface{}{
					"minAvailable": float64(1),
					"selector": map[string]interface{}{
						"matchLabels": map[string]interface{}{}, // {} = opt-in sentinel
					},
				},
			}),
		},
		"absent selector.matchLabels is valid": {
			obj: newWRT("no-match-labels", "my-worker", map[string]interface{}{
				"apiVersion": "policy/v1",
				"kind":       "PodDisruptionBudget",
				"spec": map[string]interface{}{
					"minAvailable": float64(1),
					"selector":     map[string]interface{}{},
				},
			}),
		},

		// --- Metric selector matchLabels validation ---
		// User labels (e.g. task_type) are allowed; controller-owned keys are rejected.
		"metric selector matchLabels with user label is valid": {
			obj: newWRT("metric-sel-user-label", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"kind":       "HorizontalPodAutoscaler",
				"spec": map[string]interface{}{
					"minReplicas": float64(2),
					"maxReplicas": float64(10),
					"metrics": []interface{}{
						map[string]interface{}{
							"type": "External",
							"external": map[string]interface{}{
								"metric": map[string]interface{}{
									"name": "temporal_backlog_count_by_version",
									"selector": map[string]interface{}{
										"matchLabels": map[string]interface{}{
											"task_type": "Activity",
										},
									},
								},
								"target": map[string]interface{}{
									"type":         "AverageValue",
									"averageValue": "10",
								},
							},
						},
					},
				},
			}),
		},
		"metric selector matchLabels with temporal_worker_deployment_name rejected": {
			obj: newWRT("metric-sel-wdn", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"kind":       "HorizontalPodAutoscaler",
				"spec": map[string]interface{}{
					"minReplicas": float64(2),
					"maxReplicas": float64(10),
					"metrics": []interface{}{
						map[string]interface{}{
							"type": "External",
							"external": map[string]interface{}{
								"metric": map[string]interface{}{
									"name": "temporal_backlog_count_by_version",
									"selector": map[string]interface{}{
										"matchLabels": map[string]interface{}{
											"temporal_worker_deployment_name": "default_my-worker",
										},
									},
								},
								"target": map[string]interface{}{"type": "AverageValue", "averageValue": "10"},
							},
						},
					},
				},
			}),
			errorMsg: `"temporal_worker_deployment_name" is managed by the controller`,
		},
		"metric selector matchLabels with temporal_worker_build_id rejected": {
			obj: newWRT("metric-sel-wdbid", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"kind":       "HorizontalPodAutoscaler",
				"spec": map[string]interface{}{
					"minReplicas": float64(2),
					"maxReplicas": float64(10),
					"metrics": []interface{}{
						map[string]interface{}{
							"type": "External",
							"external": map[string]interface{}{
								"metric": map[string]interface{}{
									"name": "temporal_backlog_count_by_version",
									"selector": map[string]interface{}{
										"matchLabels": map[string]interface{}{
											"temporal_worker_build_id": "abc123",
										},
									},
								},
								"target": map[string]interface{}{"type": "AverageValue", "averageValue": "10"},
							},
						},
					},
				},
			}),
			errorMsg: `"temporal_worker_build_id" is managed by the controller`,
		},
		"metric selector matchLabels with temporal_namespace rejected": {
			obj: newWRT("metric-sel-tn", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"kind":       "HorizontalPodAutoscaler",
				"spec": map[string]interface{}{
					"minReplicas": float64(2),
					"maxReplicas": float64(10),
					"metrics": []interface{}{
						map[string]interface{}{
							"type": "External",
							"external": map[string]interface{}{
								"metric": map[string]interface{}{
									"name": "temporal_backlog_count_by_version",
									"selector": map[string]interface{}{
										"matchLabels": map[string]interface{}{
											"temporal_namespace": "my-ns",
										},
									},
								},
								"target": map[string]interface{}{"type": "AverageValue", "averageValue": "10"},
							},
						},
					},
				},
			}),
			errorMsg: `"temporal_namespace" is managed by the controller`,
		},
		"empty metric selector matchLabels is valid (controller appends)": {
			obj: newWRT("metric-sel-empty", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"kind":       "HorizontalPodAutoscaler",
				"spec": map[string]interface{}{
					"minReplicas": float64(2),
					"maxReplicas": float64(10),
					"metrics": []interface{}{
						map[string]interface{}{
							"type": "External",
							"external": map[string]interface{}{
								"metric": map[string]interface{}{
									"name": "temporal_backlog_count_by_version",
									"selector": map[string]interface{}{
										"matchLabels": map[string]interface{}{},
									},
								},
								"target": map[string]interface{}{
									"type":         "AverageValue",
									"averageValue": "10",
								},
							},
						},
					},
				},
			}),
		},
		"absent metric selector matchLabels is valid": {
			obj: newWRT("metric-sel-absent", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"kind":       "HorizontalPodAutoscaler",
				"spec": map[string]interface{}{
					"minReplicas": float64(2),
					"maxReplicas": float64(10),
					"metrics": []interface{}{
						map[string]interface{}{
							"type": "External",
							"external": map[string]interface{}{
								"metric": map[string]interface{}{
									"name":     "temporal_backlog_count_by_version",
									"selector": map[string]interface{}{},
								},
								"target": map[string]interface{}{
									"type":         "AverageValue",
									"averageValue": "10",
								},
							},
						},
					},
				},
			}),
		},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			ctx := context.Background()
			v := newValidatorNoAPI()

			warnings, err := v.ValidateCreate(ctx, tc.obj)

			if tc.errorMsg != "" {
				require.Error(t, err, "expected an error containing %q", tc.errorMsg)
				assert.Contains(t, err.Error(), tc.errorMsg)
			} else {
				require.NoError(t, err)
			}
			assert.Nil(t, warnings)
		})
	}
}

func TestWorkerResourceTemplate_ValidateUpdate_Immutability(t *testing.T) {
	tests := map[string]struct {
		oldTemporalWorkerDeploymentRef string
		newTemporalWorkerDeploymentRef string
		errorMsg                       string
	}{
		"same temporalWorkerDeploymentRef is valid": {
			oldTemporalWorkerDeploymentRef: "my-worker",
			newTemporalWorkerDeploymentRef: "my-worker",
		},
		"changing temporalWorkerDeploymentRef is forbidden": {
			oldTemporalWorkerDeploymentRef: "my-worker",
			newTemporalWorkerDeploymentRef: "different-worker",
			errorMsg:                       "temporalWorkerDeploymentRef.name is immutable",
		},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			ctx := context.Background()
			v := newValidatorNoAPI()

			oldWRT := newWRT("my-hpa", tc.oldTemporalWorkerDeploymentRef, validHPAObject())
			newWRT := newWRT("my-hpa", tc.newTemporalWorkerDeploymentRef, validHPAObject())

			_, err := v.ValidateUpdate(ctx, oldWRT, newWRT)

			if tc.errorMsg != "" {
				require.Error(t, err)
				assert.Contains(t, err.Error(), tc.errorMsg)
			} else {
				require.NoError(t, err)
			}
		})
	}
}

func TestWorkerResourceTemplate_ValidateUpdate_ValidatesNewSpec(t *testing.T) {
	ctx := context.Background()
	v := newValidatorNoAPI()

	// Update from a valid spec to one with a kind not in the allowed list should fail
	oldWRT := newWRT("my-hpa", "my-worker", validHPAObject())
	invalidNew := newWRT("my-hpa", "my-worker", map[string]interface{}{
		"apiVersion": "apps/v1",
		"kind":       "Deployment",
		"spec":       map[string]interface{}{},
	})

	_, err := v.ValidateUpdate(ctx, oldWRT, invalidNew)
	require.Error(t, err)
	assert.Contains(t, err.Error(), `kind "Deployment" is not in the allowed list`)
}

func TestWorkerResourceTemplate_ValidateDelete(t *testing.T) {
	ctx := context.Background()
	v := newValidatorNoAPI()

	// No admission request is present in the context and no controller SA name is set,
	// so SubjectAccessReview calls are skipped — only the RESTMapper scope check runs.
	wrt := newWRT("my-hpa", "my-worker", validHPAObject())
	warnings, err := v.ValidateDelete(ctx, wrt)
	assert.NoError(t, err)
	assert.Nil(t, warnings)
}

func TestWorkerResourceTemplate_ValidateDelete_WrongObjectType(t *testing.T) {
	ctx := context.Background()
	v := newValidatorNoAPI()

	_, err := v.ValidateDelete(ctx, &corev1.Pod{})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "expected a WorkerResourceTemplate")
}

func TestWorkerResourceTemplate_ValidateDelete_NilRaw(t *testing.T) {
	ctx := context.Background()
	v := newValidatorNoAPI()

	// WRT with nil spec.template should be permitted (nothing to check)
	wrt := &temporaliov1alpha1.WorkerResourceTemplate{
		ObjectMeta: metav1.ObjectMeta{Name: "empty", Namespace: "default"},
		Spec: temporaliov1alpha1.WorkerResourceTemplateSpec{
			TemporalWorkerDeploymentRef: temporaliov1alpha1.TemporalWorkerDeploymentReference{Name: "my-worker"},
			Template:                    runtime.RawExtension{Raw: nil},
		},
	}
	_, err := v.ValidateDelete(ctx, wrt)
	assert.NoError(t, err)
}

func TestWorkerResourceTemplate_ValidateCreate_WrongObjectType(t *testing.T) {
	ctx := context.Background()
	v := newValidatorNoAPI()

	_, err := v.ValidateCreate(ctx, &corev1.Pod{})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "expected a WorkerResourceTemplate")
}

func TestWorkerResourceTemplate_ValidateUpdate_WrongObjectType(t *testing.T) {
	ctx := context.Background()
	v := newValidatorNoAPI()

	_, err := v.ValidateUpdate(ctx, &corev1.Pod{}, newWRT("x", "w", validHPAObject()))
	require.Error(t, err)
	assert.Contains(t, err.Error(), "expected a WorkerResourceTemplate for old object")

	_, err = v.ValidateUpdate(ctx, newWRT("x", "w", validHPAObject()), &corev1.Pod{})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "expected a WorkerResourceTemplate for new object")
}

func TestWorkerResourceTemplate_AllowedKinds(t *testing.T) {
	ctx := context.Background()

	// Validator with an explicit allow list: only MyScaler is permitted.
	v := &temporaliov1alpha1.WorkerResourceTemplateValidator{
		Client: fake.NewClientBuilder().Build(),
		RESTMapper: newFakeRESTMapper(
			schema.GroupVersionKind{Group: "example.com", Version: "v1", Kind: "MyScaler"},
		),
		AllowedKinds: []string{"MyScaler"},
	}

	// MyScaler is in the allowed list — passes kind check and namespace-scope check.
	_, err := v.ValidateCreate(ctx, newWRT("ok", "my-worker", map[string]interface{}{
		"apiVersion": "example.com/v1",
		"kind":       "MyScaler",
		"spec":       map[string]interface{}{},
	}))
	require.NoError(t, err, "MyScaler should be allowed when it is in the AllowedKinds list")

	// HPA is NOT in this allow list — rejected before reaching the API checks.
	_, err = v.ValidateCreate(ctx, newWRT("hpa", "my-worker", validHPAObject()))
	require.Error(t, err)
	assert.Contains(t, err.Error(), `kind "HorizontalPodAutoscaler" is not in the allowed list`)

	// Validator with empty AllowedKinds: all kinds are rejected (deny-all) before API checks.
	vEmpty := &temporaliov1alpha1.WorkerResourceTemplateValidator{
		Client:     fake.NewClientBuilder().Build(),
		RESTMapper: newFakeRESTMapper(),
	}
	_, err = vEmpty.ValidateCreate(ctx, newWRT("deploy", "my-worker", map[string]interface{}{
		"apiVersion": "apps/v1",
		"kind":       "Deployment",
		"spec":       map[string]interface{}{},
	}))
	require.Error(t, err, "Deployment should be rejected when AllowedKinds is empty (deny-all)")
	assert.Contains(t, err.Error(), `kind "Deployment" is not in the allowed list`)
}

func TestWorkerResourceTemplate_MultipleErrors(t *testing.T) {
	ctx := context.Background()
	v := newValidatorNoAPI()

	// Both metadata.name and minReplicas=0 are invalid
	obj := map[string]interface{}{
		"apiVersion": "autoscaling/v2",
		"kind":       "HorizontalPodAutoscaler",
		"metadata":   map[string]interface{}{"name": "bad-name"},
		"spec": map[string]interface{}{
			"minReplicas": float64(0),
			"maxReplicas": float64(5),
		},
	}
	_, err := v.ValidateCreate(ctx, newWRT("multi-err", "my-worker", obj))
	require.Error(t, err)
	assert.Contains(t, err.Error(), "metadata.name is generated by the controller")
	assert.Contains(t, err.Error(), "minReplicas must not be 0")
}
