package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// TemporalWorkerDeploymentReference references a TemporalWorkerDeployment in the same Kubernetes namespace.
type TemporalWorkerDeploymentReference struct {
	// Name of the TemporalWorkerDeployment resource in the same namespace.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Pattern=`^[a-z0-9]([-a-z0-9]*[a-z0-9])?$`
	Name string `json:"name"`
}

// WorkerResourceTemplateSpec defines the desired state of WorkerResourceTemplate.
type WorkerResourceTemplateSpec struct {
	// TemporalWorkerDeploymentRef references the TemporalWorkerDeployment to attach this resource to.
	// +kubebuilder:validation:Required
	TemporalWorkerDeploymentRef TemporalWorkerDeploymentReference `json:"temporalWorkerDeploymentRef"`

	// Template is the Kubernetes resource template applied per active Build ID.
	// Must include apiVersion, kind, and spec. metadata.name and metadata.namespace
	// are generated by the controller; do not set them.
	//
	// String values in the spec may use Go template expressions:
	//   {{ .K8sNamespace }}, {{ .TWDName }}, {{ .TemporalNamespace }}, {{ .BuildID }}
	//
	// The controller auto-injects two well-known fields when present as an empty object:
	//   scaleTargetRef: {} - injected to point at the versioned Deployment (HPA, WPA, etc.)
	//   matchLabels: {}    - injected with the versioned Deployment selector labels (PDB, etc.)
	// +kubebuilder:validation:Required
	// +kubebuilder:pruning:PreserveUnknownFields
	Template runtime.RawExtension `json:"template"`
}

const (
	// ConditionTypeReady is the condition type that reports whether all active
	// Build ID instances of this WorkerResourceTemplate have been successfully applied.
	// Using the standard "Ready" type makes this condition visible to helm install --wait
	// and kubectl apply --wait.
	//
	// True:    all active Build ID instances applied successfully at the current template generation.
	// False:   one or more instances failed to apply (see Message for the error).
	// Unknown: no apply has been attempted yet (e.g. the WRT was just created).
	ConditionTypeReady = "Ready"

	// ReasonWRTAllVersionsApplied is the condition reason when all instances are successfully applied.
	ReasonWRTAllVersionsApplied = "AllVersionsApplied"
	// ReasonWRTApplyFailed is the condition reason when one or more instances failed to apply.
	ReasonWRTApplyFailed = "ApplyFailed"
	// ReasonWRTTWDNotFound is the condition reason when the referenced TemporalWorkerDeployment does not exist.
	ReasonWRTTWDNotFound = "TemporalWorkerDeploymentNotFound"
)

// WorkerResourceTemplateVersionStatus describes the per-Build-ID apply status of a WorkerResourceTemplate.
type WorkerResourceTemplateVersionStatus struct {
	// BuildID is the Build ID of the versioned Deployment this entry refers to.
	BuildID string `json:"buildID"`

	// ResourceName is the name of the applied Kubernetes resource.
	// +optional
	ResourceName string `json:"resourceName,omitempty"`

	// LastAppliedGeneration is the WorkerResourceTemplate metadata.generation at the time
	// of the last **successful** apply for this Build ID. A value of 0 means no successful
	// apply has occurred yet.
	//
	// Reading the status:
	//   - 0                                  → never applied
	//   - 0 < lastAppliedGeneration < .metadata.generation → older spec applied; current spec pending or failing (see Message)
	//   - lastAppliedGeneration == .metadata.generation    → healthy, up-to-date
	//   - lastAppliedGeneration > 0 && message != ""       → previously applied at that generation; current apply failing
	// +optional
	LastAppliedGeneration int64 `json:"lastAppliedGeneration,omitempty"`

	// ApplyError is non-empty when the most recent apply attempt failed.
	// +optional
	ApplyError string `json:"applyError,omitempty"`

	// LastAppliedHash is a hash of the rendered resource as of the last successful apply.
	// The controller uses this internally to skip redundant SSA apply calls when the
	// rendered output has not changed. Users can treat this as an opaque value.
	// +optional
	LastAppliedHash string `json:"lastAppliedHash,omitempty"`

	// LastTransitionTime is the last time this status entry changed.
	LastTransitionTime metav1.Time `json:"lastTransitionTime"`
}

// WorkerResourceTemplateStatus defines the observed state of WorkerResourceTemplate.
type WorkerResourceTemplateStatus struct {
	// Versions describes the per-Build-ID status of worker resource template instances.
	// +optional
	Versions []WorkerResourceTemplateVersionStatus `json:"versions,omitempty"`

	// Conditions describe the current state of the WorkerResourceTemplate.
	// The Ready condition is True when all active Build ID instances have been
	// successfully applied with the current template generation.
	// +optional
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

//+kubebuilder:object:root=true
//+kubebuilder:subresource:status
//+kubebuilder:resource:shortName=wrt
//+kubebuilder:printcolumn:name="Worker",type="string",JSONPath=".spec.temporalWorkerDeploymentRef.name",description="Referenced TemporalWorkerDeployment"
//+kubebuilder:printcolumn:name="Kind",type="string",JSONPath=".spec.template.kind",description="Kind of owned resource"
//+kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",description="Age"

// WorkerResourceTemplate attaches an arbitrary namespaced Kubernetes resource
// (HPA, PDB, WPA, custom CRDs, etc.) to each per-Build-ID versioned Deployment
// managed by a TemporalWorkerDeployment. One copy of the resource is created per
// active Build ID, owned by this WorkerResourceTemplate (so all copies are deleted
// when the WorkerResourceTemplate itself is deleted).
type WorkerResourceTemplate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   WorkerResourceTemplateSpec   `json:"spec,omitempty"`
	Status WorkerResourceTemplateStatus `json:"status,omitempty"`
}

//+kubebuilder:object:root=true

// WorkerResourceTemplateList contains a list of WorkerResourceTemplate.
type WorkerResourceTemplateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WorkerResourceTemplate `json:"items"`
}

func init() {
	SchemeBuilder.Register(&WorkerResourceTemplate{}, &WorkerResourceTemplateList{})
}
