package v1alpha1_test

import (
	"context"
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	temporaliov1alpha1 "github.com/temporalio/temporal-worker-controller/api/v1alpha1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// newWRT builds a WorkerResourceTemplate with an arbitrary embedded object spec.
func newWRT(name, temporalWorkerDeploymentRefName string, embeddedObj map[string]interface{}) *temporaliov1alpha1.WorkerResourceTemplate {
	raw, _ := json.Marshal(embeddedObj)
	return &temporaliov1alpha1.WorkerResourceTemplate{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: "default",
		},
		Spec: temporaliov1alpha1.WorkerResourceTemplateSpec{
			TemporalWorkerDeploymentRef: temporaliov1alpha1.TemporalWorkerDeploymentReference{
				Name: temporalWorkerDeploymentRefName,
			},
			Template: runtime.RawExtension{Raw: raw},
		},
	}
}

// validHPAObject returns a minimal valid HPA embedded object spec.
func validHPAObject() map[string]interface{} {
	return map[string]interface{}{
		"apiVersion": "autoscaling/v2",
		"kind":       "HorizontalPodAutoscaler",
		"spec": map[string]interface{}{
			"minReplicas": float64(2),
			"maxReplicas": float64(10),
		},
	}
}

// newValidatorNoAPI creates a validator with no API client (API checks skipped).
// AllowedKinds mirrors the default Helm values (HPA + PDB) so that most tests
// use realistic allowed kinds while kinds like Deployment remain disallowed.
func newValidatorNoAPI() *temporaliov1alpha1.WorkerResourceTemplateValidator {
	return &temporaliov1alpha1.WorkerResourceTemplateValidator{
		AllowedKinds: []string{"HorizontalPodAutoscaler", "PodDisruptionBudget"},
	}
}

func TestWorkerResourceTemplate_ValidateCreate(t *testing.T) {
	tests := map[string]struct {
		obj      runtime.Object
		errorMsg string
	}{
		"valid HPA": {
			obj: newWRT("my-hpa", "my-worker", validHPAObject()),
		},
		"wrong object type": {
			obj:      &corev1.Pod{ObjectMeta: metav1.ObjectMeta{Name: "pod"}},
			errorMsg: "expected a WorkerResourceTemplate",
		},
		"nil raw object": {
			obj: &temporaliov1alpha1.WorkerResourceTemplate{
				ObjectMeta: metav1.ObjectMeta{Name: "empty", Namespace: "default"},
				Spec: temporaliov1alpha1.WorkerResourceTemplateSpec{
					TemporalWorkerDeploymentRef: temporaliov1alpha1.TemporalWorkerDeploymentReference{Name: "my-worker"},
					Template:                    runtime.RawExtension{Raw: nil},
				},
			},
			errorMsg: "object must be specified",
		},
		"missing apiVersion": {
			obj: newWRT("no-apiv", "my-worker", map[string]interface{}{
				"kind": "HorizontalPodAutoscaler",
				"spec": map[string]interface{}{"minReplicas": float64(1)},
			}),
			errorMsg: "apiVersion must be specified",
		},
		"missing kind": {
			obj: newWRT("no-kind", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"spec":       map[string]interface{}{"minReplicas": float64(1)},
			}),
			errorMsg: "kind must be specified",
		},
		"metadata.name set in embedded object": {
			obj: newWRT("has-name", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"kind":       "HorizontalPodAutoscaler",
				"metadata":   map[string]interface{}{"name": "fixed-name"},
				"spec":       map[string]interface{}{"minReplicas": float64(2)},
			}),
			errorMsg: "metadata.name is generated by the controller",
		},
		"metadata.namespace set in embedded object": {
			obj: newWRT("has-ns", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"kind":       "HorizontalPodAutoscaler",
				"metadata":   map[string]interface{}{"namespace": "some-ns"},
				"spec":       map[string]interface{}{"minReplicas": float64(2)},
			}),
			errorMsg: "metadata.namespace is set by the controller",
		},
		"kind not in allowed list — Deployment": {
			obj: newWRT("bad-deploy", "my-worker", map[string]interface{}{
				"apiVersion": "apps/v1",
				"kind":       "Deployment",
				"spec":       map[string]interface{}{},
			}),
			errorMsg: `kind "Deployment" is not in the allowed list`,
		},
		"kind not in allowed list — StatefulSet": {
			obj: newWRT("bad-sts", "my-worker", map[string]interface{}{
				"apiVersion": "apps/v1",
				"kind":       "StatefulSet",
				"spec":       map[string]interface{}{},
			}),
			errorMsg: `kind "StatefulSet" is not in the allowed list`,
		},
		"kind not in allowed list — Pod": {
			obj: newWRT("bad-pod", "my-worker", map[string]interface{}{
				"apiVersion": "v1",
				"kind":       "Pod",
				"spec":       map[string]interface{}{},
			}),
			errorMsg: `kind "Pod" is not in the allowed list`,
		},
		"allowed kind check is case-insensitive": {
			obj: newWRT("bad-job", "my-worker", map[string]interface{}{
				"apiVersion": "batch/v1",
				"kind":       "job", // lowercase — not in allowed list
				"spec":       map[string]interface{}{},
			}),
			errorMsg: `kind "job" is not in the allowed list`,
		},
		"minReplicas is 0": {
			obj: newWRT("zero-replicas", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"kind":       "HorizontalPodAutoscaler",
				"spec": map[string]interface{}{
					"minReplicas": float64(0),
					"maxReplicas": float64(5),
				},
			}),
			errorMsg: "minReplicas must not be 0",
		},
		"non-null scaleTargetRef": {
			obj: newWRT("has-scale-ref", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"kind":       "HorizontalPodAutoscaler",
				"spec": map[string]interface{}{
					"scaleTargetRef": map[string]interface{}{
						"apiVersion": "apps/v1",
						"kind":       "Deployment",
						"name":       "some-other-deployment",
					},
					"minReplicas": float64(2),
					"maxReplicas": float64(10),
				},
			}),
			errorMsg: "if scaleTargetRef is present, the controller owns it",
		},
		"null scaleTargetRef is valid (opt-in)": {
			obj: newWRT("null-scale-ref", "my-worker", map[string]interface{}{
				"apiVersion": "autoscaling/v2",
				"kind":       "HorizontalPodAutoscaler",
				"spec": map[string]interface{}{
					"scaleTargetRef": nil, // null = opt-in sentinel
					"minReplicas":    float64(2),
					"maxReplicas":    float64(10),
				},
			}),
		},
		"non-null selector.matchLabels": {
			obj: newWRT("has-match-labels", "my-worker", map[string]interface{}{
				"apiVersion": "policy/v1",
				"kind":       "PodDisruptionBudget",
				"spec": map[string]interface{}{
					"minAvailable": float64(1),
					"selector": map[string]interface{}{
						"matchLabels": map[string]interface{}{
							"app": "my-worker",
						},
					},
				},
			}),
			errorMsg: "if selector.matchLabels is present, the controller owns it",
		},
		"null selector.matchLabels is valid (opt-in)": {
			obj: newWRT("null-match-labels", "my-worker", map[string]interface{}{
				"apiVersion": "policy/v1",
				"kind":       "PodDisruptionBudget",
				"spec": map[string]interface{}{
					"minAvailable": float64(1),
					"selector": map[string]interface{}{
						"matchLabels": nil, // null = opt-in sentinel
					},
				},
			}),
		},
		"absent selector.matchLabels is valid": {
			obj: newWRT("no-match-labels", "my-worker", map[string]interface{}{
				"apiVersion": "policy/v1",
				"kind":       "PodDisruptionBudget",
				"spec": map[string]interface{}{
					"minAvailable": float64(1),
					"selector":     map[string]interface{}{},
				},
			}),
		},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			ctx := context.Background()
			v := newValidatorNoAPI()

			warnings, err := v.ValidateCreate(ctx, tc.obj)

			if tc.errorMsg != "" {
				require.Error(t, err, "expected an error containing %q", tc.errorMsg)
				assert.Contains(t, err.Error(), tc.errorMsg)
			} else {
				require.NoError(t, err)
			}
			assert.Nil(t, warnings)
		})
	}
}

func TestWorkerResourceTemplate_ValidateUpdate_Immutability(t *testing.T) {
	tests := map[string]struct {
		oldTemporalWorkerDeploymentRef string
		newTemporalWorkerDeploymentRef string
		errorMsg                       string
	}{
		"same temporalWorkerDeploymentRef is valid": {
			oldTemporalWorkerDeploymentRef: "my-worker",
			newTemporalWorkerDeploymentRef: "my-worker",
		},
		"changing temporalWorkerDeploymentRef is forbidden": {
			oldTemporalWorkerDeploymentRef: "my-worker",
			newTemporalWorkerDeploymentRef: "different-worker",
			errorMsg:                       "temporalWorkerDeploymentRef.name is immutable",
		},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			ctx := context.Background()
			v := newValidatorNoAPI()

			oldWRT := newWRT("my-hpa", tc.oldTemporalWorkerDeploymentRef, validHPAObject())
			newWRT := newWRT("my-hpa", tc.newTemporalWorkerDeploymentRef, validHPAObject())

			_, err := v.ValidateUpdate(ctx, oldWRT, newWRT)

			if tc.errorMsg != "" {
				require.Error(t, err)
				assert.Contains(t, err.Error(), tc.errorMsg)
			} else {
				require.NoError(t, err)
			}
		})
	}
}

func TestWorkerResourceTemplate_ValidateUpdate_ValidatesNewSpec(t *testing.T) {
	ctx := context.Background()
	v := newValidatorNoAPI()

	// Update from a valid spec to one with a kind not in the allowed list should fail
	oldWRT := newWRT("my-hpa", "my-worker", validHPAObject())
	invalidNew := newWRT("my-hpa", "my-worker", map[string]interface{}{
		"apiVersion": "apps/v1",
		"kind":       "Deployment",
		"spec":       map[string]interface{}{},
	})

	_, err := v.ValidateUpdate(ctx, oldWRT, invalidNew)
	require.Error(t, err)
	assert.Contains(t, err.Error(), `kind "Deployment" is not in the allowed list`)
}

func TestWorkerResourceTemplate_ValidateDelete(t *testing.T) {
	ctx := context.Background()
	v := newValidatorNoAPI()

	// When API client is nil, delete permission checks are skipped
	wrt := newWRT("my-hpa", "my-worker", validHPAObject())
	warnings, err := v.ValidateDelete(ctx, wrt)
	assert.NoError(t, err)
	assert.Nil(t, warnings)
}

func TestWorkerResourceTemplate_ValidateDelete_WrongObjectType(t *testing.T) {
	ctx := context.Background()
	v := newValidatorNoAPI()

	_, err := v.ValidateDelete(ctx, &corev1.Pod{})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "expected a WorkerResourceTemplate")
}

func TestWorkerResourceTemplate_ValidateDelete_NilRaw(t *testing.T) {
	ctx := context.Background()
	v := newValidatorNoAPI()

	// WRT with nil spec.template should be permitted (nothing to check)
	wrt := &temporaliov1alpha1.WorkerResourceTemplate{
		ObjectMeta: metav1.ObjectMeta{Name: "empty", Namespace: "default"},
		Spec: temporaliov1alpha1.WorkerResourceTemplateSpec{
			TemporalWorkerDeploymentRef: temporaliov1alpha1.TemporalWorkerDeploymentReference{Name: "my-worker"},
			Template:                    runtime.RawExtension{Raw: nil},
		},
	}
	_, err := v.ValidateDelete(ctx, wrt)
	assert.NoError(t, err)
}

func TestWorkerResourceTemplate_ValidateCreate_WrongObjectType(t *testing.T) {
	ctx := context.Background()
	v := newValidatorNoAPI()

	_, err := v.ValidateCreate(ctx, &corev1.Pod{})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "expected a WorkerResourceTemplate")
}

func TestWorkerResourceTemplate_ValidateUpdate_WrongObjectType(t *testing.T) {
	ctx := context.Background()
	v := newValidatorNoAPI()

	_, err := v.ValidateUpdate(ctx, &corev1.Pod{}, newWRT("x", "w", validHPAObject()))
	require.Error(t, err)
	assert.Contains(t, err.Error(), "expected a WorkerResourceTemplate for old object")

	_, err = v.ValidateUpdate(ctx, newWRT("x", "w", validHPAObject()), &corev1.Pod{})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "expected a WorkerResourceTemplate for new object")
}

func TestWorkerResourceTemplate_AllowedKinds(t *testing.T) {
	ctx := context.Background()

	// Validator with an explicit allow list: only MyScaler is permitted.
	v := &temporaliov1alpha1.WorkerResourceTemplateValidator{
		AllowedKinds: []string{"MyScaler"},
	}

	// MyScaler is in the allowed list — passes kind check (API checks skipped).
	_, err := v.ValidateCreate(ctx, newWRT("ok", "my-worker", map[string]interface{}{
		"apiVersion": "example.com/v1",
		"kind":       "MyScaler",
		"spec":       map[string]interface{}{},
	}))
	require.NoError(t, err, "MyScaler should be allowed when it is in the AllowedKinds list")

	// HPA is NOT in this allow list — should be rejected.
	_, err = v.ValidateCreate(ctx, newWRT("hpa", "my-worker", validHPAObject()))
	require.Error(t, err)
	assert.Contains(t, err.Error(), `kind "HorizontalPodAutoscaler" is not in the allowed list`)

	// Validator with empty AllowedKinds: all kinds are rejected (deny-all).
	vEmpty := &temporaliov1alpha1.WorkerResourceTemplateValidator{}
	_, err = vEmpty.ValidateCreate(ctx, newWRT("deploy", "my-worker", map[string]interface{}{
		"apiVersion": "apps/v1",
		"kind":       "Deployment",
		"spec":       map[string]interface{}{},
	}))
	require.Error(t, err, "Deployment should be rejected when AllowedKinds is empty (deny-all)")
	assert.Contains(t, err.Error(), `kind "Deployment" is not in the allowed list`)
}

func TestWorkerResourceTemplate_MultipleErrors(t *testing.T) {
	ctx := context.Background()
	v := newValidatorNoAPI()

	// Both metadata.name and minReplicas=0 are invalid
	obj := map[string]interface{}{
		"apiVersion": "autoscaling/v2",
		"kind":       "HorizontalPodAutoscaler",
		"metadata":   map[string]interface{}{"name": "bad-name"},
		"spec": map[string]interface{}{
			"minReplicas": float64(0),
			"maxReplicas": float64(5),
		},
	}
	_, err := v.ValidateCreate(ctx, newWRT("multi-err", "my-worker", obj))
	require.Error(t, err)
	assert.Contains(t, err.Error(), "metadata.name is generated by the controller")
	assert.Contains(t, err.Error(), "minReplicas must not be 0")
}
