//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllAtOnceRolloutStrategy) DeepCopyInto(out *AllAtOnceRolloutStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllAtOnceRolloutStrategy.
func (in *AllAtOnceRolloutStrategy) DeepCopy() *AllAtOnceRolloutStrategy {
	if in == nil {
		return nil
	}
	out := new(AllAtOnceRolloutStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseWorkerDeploymentVersion) DeepCopyInto(out *BaseWorkerDeploymentVersion) {
	*out = *in
	if in.HealthySince != nil {
		in, out := &in.HealthySince, &out.HealthySince
		*out = (*in).DeepCopy()
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.TaskQueues != nil {
		in, out := &in.TaskQueues, &out.TaskQueues
		*out = make([]TaskQueue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseWorkerDeploymentVersion.
func (in *BaseWorkerDeploymentVersion) DeepCopy() *BaseWorkerDeploymentVersion {
	if in == nil {
		return nil
	}
	out := new(BaseWorkerDeploymentVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrentWorkerDeploymentVersion) DeepCopyInto(out *CurrentWorkerDeploymentVersion) {
	*out = *in
	in.BaseWorkerDeploymentVersion.DeepCopyInto(&out.BaseWorkerDeploymentVersion)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrentWorkerDeploymentVersion.
func (in *CurrentWorkerDeploymentVersion) DeepCopy() *CurrentWorkerDeploymentVersion {
	if in == nil {
		return nil
	}
	out := new(CurrentWorkerDeploymentVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeprecatedWorkerDeploymentVersion) DeepCopyInto(out *DeprecatedWorkerDeploymentVersion) {
	*out = *in
	in.BaseWorkerDeploymentVersion.DeepCopyInto(&out.BaseWorkerDeploymentVersion)
	if in.DrainedSince != nil {
		in, out := &in.DrainedSince, &out.DrainedSince
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeprecatedWorkerDeploymentVersion.
func (in *DeprecatedWorkerDeploymentVersion) DeepCopy() *DeprecatedWorkerDeploymentVersion {
	if in == nil {
		return nil
	}
	out := new(DeprecatedWorkerDeploymentVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GateWorkflowConfig) DeepCopyInto(out *GateWorkflowConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GateWorkflowConfig.
func (in *GateWorkflowConfig) DeepCopy() *GateWorkflowConfig {
	if in == nil {
		return nil
	}
	out := new(GateWorkflowConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedField) DeepCopyInto(out *ManagedField) {
	*out = *in
	if in.V1 != nil {
		in, out := &in.V1, &out.V1
		*out = make([]V1Field, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedField.
func (in *ManagedField) DeepCopy() *ManagedField {
	if in == nil {
		return nil
	}
	out := new(ManagedField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManualRolloutStrategy) DeepCopyInto(out *ManualRolloutStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManualRolloutStrategy.
func (in *ManualRolloutStrategy) DeepCopy() *ManualRolloutStrategy {
	if in == nil {
		return nil
	}
	out := new(ManualRolloutStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueStatistics) DeepCopyInto(out *QueueStatistics) {
	*out = *in
	out.ApproximateBacklogAge = in.ApproximateBacklogAge
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueStatistics.
func (in *QueueStatistics) DeepCopy() *QueueStatistics {
	if in == nil {
		return nil
	}
	out := new(QueueStatistics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutStep) DeepCopyInto(out *RolloutStep) {
	*out = *in
	out.PauseDuration = in.PauseDuration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutStep.
func (in *RolloutStep) DeepCopy() *RolloutStep {
	if in == nil {
		return nil
	}
	out := new(RolloutStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutStrategy) DeepCopyInto(out *RolloutStrategy) {
	*out = *in
	if in.Gate != nil {
		in, out := &in.Gate, &out.Gate
		*out = new(GateWorkflowConfig)
		**out = **in
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]RolloutStep, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutStrategy.
func (in *RolloutStrategy) DeepCopy() *RolloutStrategy {
	if in == nil {
		return nil
	}
	out := new(RolloutStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SunsetStrategy) DeepCopyInto(out *SunsetStrategy) {
	*out = *in
	if in.ScaledownDelay != nil {
		in, out := &in.ScaledownDelay, &out.ScaledownDelay
		*out = new(v1.Duration)
		**out = **in
	}
	if in.DeleteDelay != nil {
		in, out := &in.DeleteDelay, &out.DeleteDelay
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SunsetStrategy.
func (in *SunsetStrategy) DeepCopy() *SunsetStrategy {
	if in == nil {
		return nil
	}
	out := new(SunsetStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetWorkerDeploymentVersion) DeepCopyInto(out *TargetWorkerDeploymentVersion) {
	*out = *in
	in.BaseWorkerDeploymentVersion.DeepCopyInto(&out.BaseWorkerDeploymentVersion)
	if in.TestWorkflows != nil {
		in, out := &in.TestWorkflows, &out.TestWorkflows
		*out = make([]WorkflowExecution, len(*in))
		copy(*out, *in)
	}
	if in.RampPercentage != nil {
		in, out := &in.RampPercentage, &out.RampPercentage
		*out = new(float32)
		**out = **in
	}
	if in.RampingSince != nil {
		in, out := &in.RampingSince, &out.RampingSince
		*out = (*in).DeepCopy()
	}
	if in.RampLastModifiedAt != nil {
		in, out := &in.RampLastModifiedAt, &out.RampLastModifiedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetWorkerDeploymentVersion.
func (in *TargetWorkerDeploymentVersion) DeepCopy() *TargetWorkerDeploymentVersion {
	if in == nil {
		return nil
	}
	out := new(TargetWorkerDeploymentVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskQueue) DeepCopyInto(out *TaskQueue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskQueue.
func (in *TaskQueue) DeepCopy() *TaskQueue {
	if in == nil {
		return nil
	}
	out := new(TaskQueue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalConnection) DeepCopyInto(out *TemporalConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalConnection.
func (in *TemporalConnection) DeepCopy() *TemporalConnection {
	if in == nil {
		return nil
	}
	out := new(TemporalConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TemporalConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalConnectionList) DeepCopyInto(out *TemporalConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TemporalConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalConnectionList.
func (in *TemporalConnectionList) DeepCopy() *TemporalConnectionList {
	if in == nil {
		return nil
	}
	out := new(TemporalConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TemporalConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalConnectionSpec) DeepCopyInto(out *TemporalConnectionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalConnectionSpec.
func (in *TemporalConnectionSpec) DeepCopy() *TemporalConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(TemporalConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalConnectionStatus) DeepCopyInto(out *TemporalConnectionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalConnectionStatus.
func (in *TemporalConnectionStatus) DeepCopy() *TemporalConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(TemporalConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalWorkerDeployment) DeepCopyInto(out *TemporalWorkerDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalWorkerDeployment.
func (in *TemporalWorkerDeployment) DeepCopy() *TemporalWorkerDeployment {
	if in == nil {
		return nil
	}
	out := new(TemporalWorkerDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TemporalWorkerDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalWorkerDeploymentList) DeepCopyInto(out *TemporalWorkerDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TemporalWorkerDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalWorkerDeploymentList.
func (in *TemporalWorkerDeploymentList) DeepCopy() *TemporalWorkerDeploymentList {
	if in == nil {
		return nil
	}
	out := new(TemporalWorkerDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TemporalWorkerDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalWorkerDeploymentSpec) DeepCopyInto(out *TemporalWorkerDeploymentSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.Template.DeepCopyInto(&out.Template)
	if in.ProgressDeadlineSeconds != nil {
		in, out := &in.ProgressDeadlineSeconds, &out.ProgressDeadlineSeconds
		*out = new(int32)
		**out = **in
	}
	in.RolloutStrategy.DeepCopyInto(&out.RolloutStrategy)
	in.SunsetStrategy.DeepCopyInto(&out.SunsetStrategy)
	out.WorkerOptions = in.WorkerOptions
	if in.MaxVersions != nil {
		in, out := &in.MaxVersions, &out.MaxVersions
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalWorkerDeploymentSpec.
func (in *TemporalWorkerDeploymentSpec) DeepCopy() *TemporalWorkerDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(TemporalWorkerDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalWorkerDeploymentStatus) DeepCopyInto(out *TemporalWorkerDeploymentStatus) {
	*out = *in
	in.TargetVersion.DeepCopyInto(&out.TargetVersion)
	if in.CurrentVersion != nil {
		in, out := &in.CurrentVersion, &out.CurrentVersion
		*out = new(CurrentWorkerDeploymentVersion)
		(*in).DeepCopyInto(*out)
	}
	if in.DeprecatedVersions != nil {
		in, out := &in.DeprecatedVersions, &out.DeprecatedVersions
		*out = make([]*DeprecatedWorkerDeploymentVersion, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DeprecatedWorkerDeploymentVersion)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.VersionConflictToken != nil {
		in, out := &in.VersionConflictToken, &out.VersionConflictToken
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.ManagedFields != nil {
		in, out := &in.ManagedFields, &out.ManagedFields
		*out = make([]*ManagedField, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ManagedField)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalWorkerDeploymentStatus.
func (in *TemporalWorkerDeploymentStatus) DeepCopy() *TemporalWorkerDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(TemporalWorkerDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerOptions) DeepCopyInto(out *WorkerOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerOptions.
func (in *WorkerOptions) DeepCopy() *WorkerOptions {
	if in == nil {
		return nil
	}
	out := new(WorkerOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowExecution) DeepCopyInto(out *WorkflowExecution) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowExecution.
func (in *WorkflowExecution) DeepCopy() *WorkflowExecution {
	if in == nil {
		return nil
	}
	out := new(WorkflowExecution)
	in.DeepCopyInto(out)
	return out
}
