name: 'Docker Hub Login'
description: 'Login to Docker Hub registry'
runs:
  using: 'composite'
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PAT }}