# This template creates a TemporalWorkerDeployment custom resource that manages
# the lifecycle of Temporal worker pods, including progressive rollouts and scaling
apiVersion: temporal.io/v1alpha1
kind: TemporalWorkerDeployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "helloworld.labels" . | nindent 4 }}
spec:
  # Configuration for connecting to Temporal
  workerOptions:
    connectionRef:
      name: {{ .Values.temporal.connectionName | default .Release.Name }}
    temporalNamespace: "{{ .Values.temporal.namespace }}"
  # How to roll out new workflow executions to the latest worker version
  rollout:
    strategy: {{ .Values.rollout.strategy }}
{{- if eq .Values.rollout.strategy "Progressive" }}
    steps:
      - rampPercentage: 1
        pauseDuration: 30s
      - rampPercentage: 10
        pauseDuration: 30s
      - rampPercentage: 50
        pauseDuration: 1m
{{- end }}
    gate:
      workflowType: "RolloutGate"
  sunset:
    scaledownDelay: 30s
    deleteDelay: 24h
  # Desired number of worker replicas
  replicas: 1
  # Desired specification for worker pods
  template:
    spec:
      containers:
        - name: main
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          readinessProbe:
            httpGet:
              port: 8080
          env:
            - name: TEMPORAL_TASK_QUEUE
              value: "{{ .Release.Namespace }}/{{ .Release.Name }}"
