apiVersion: temporal.io/v1alpha1
kind: TemporalWorkerDeployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "helloworld.labels" . | nindent 4 }}
spec:
  # Configuration for connecting to Temporal
  workerOptions:
    connectionRef:
      name: {{ .Values.temporal.connectionName | default .Release.Name) }}
    temporalNamespace: "{{ .Values.temporal.namespace }}"
  # How to rollout new workflow executions to the latest worker version
  rollout:
    strategy: {{ .Values.rollout.strategy }}
    steps:
{{- range .Values.rollout.steps }}
      - rampPercentage: {{ .rampPercentage }}
        pauseDuration: {{ .pauseDuration }}
{{- end }}
    gate:
      workflowType: "HelloWorld"
  sunset:
    scaledownDelay: {{ .Values.sunset.scaledownDelay }}
    deleteDelay: {{ .Values.sunset.deleteDelay }}
  # Desired number of worker replicas
  replicas: {{ .Values.replicas }}
  # Desired specification for worker pods
  template:
    spec:
      containers:
        - name: main
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          readinessProbe:
            httpGet:
              port: 8080
          env:
            - name: TEMPORAL_TASK_QUEUE
              value: "{{ .Release.Namespace }}-{{ .Release.Name }}"
