image:
  repository: helloworld
  tag: latest

temporal:
  namespace: "test-namespace"
  hostPort: "test.tmprl.cloud:7233"
  tlsSecretName: temporal-cloud-mtls

rollout:
  strategy: Progressive
  steps:
    - rampPercentage: 10
      pauseDuration: 30s
    - rampPercentage: 50
      pauseDuration: 1m
    - rampPercentage: 100
      pauseDuration: 30s

sunset:
  scaledownDelay: 30s
  deleteDelay: 1m

replicas: 2