# The following manifests contain a self-signed issuer CR and a certificate CR.
# More document can be found at https://docs.cert-manager.io
# WARNING: Targets CertManager v1.0. Check https://cert-manager.io/docs/installation/upgrading/ for breaking changes.
{{- if .Values.certmanager.enabled }}
{{ fail "certmanager isn't supported yet" }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/component: certificate
    {{ include "temporal-worker-controller.labels" $ | indent 4 }}
  name: selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: certificate
    {{ include "temporal-worker-controller.labels" $ | indent 4 }}
  name: serving-cert  # this name should match the one appeared in kustomizeconfig.yaml
  namespace: {{ .Release.Namespace }}
spec:
  # SERVICE_NAME and SERVICE_NAMESPACE will be substituted by kustomize TODO (carlydf): What should these be?
  dnsNames:
    - SERVICE_NAME.SERVICE_NAMESPACE.svc
    - SERVICE_NAME.SERVICE_NAMESPACE.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: webhook-server-cert # this secret will not be prefixed, since it's not managed by kustomize
---
{{- end }}