name: Helm Chart Validation

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  helm-lint:
    name: Lint Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Build chart dependencies
        run: helm repo add jetstack https://charts.jetstack.io && helm dependency build helm/temporal-worker-controller

      - name: Lint chart
        run: helm lint --strict helm/temporal-worker-controller

  helm-template:
    name: Template Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Build chart dependencies
        run: helm repo add jetstack https://charts.jetstack.io && helm dependency build helm/temporal-worker-controller

      - name: Template with default values
        run: helm template test-release helm/temporal-worker-controller

      - name: Template with namespace creation
        run: |
          helm template test-release helm/temporal-worker-controller \
            --set namespace.create=true

      - name: Template with auth proxy disabled
        run: |
          helm template test-release helm/temporal-worker-controller \
            --set authProxy.enabled=false \
            --set metrics.disableAuth=true

  helm-lint-crds:
    name: Lint CRDs Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Lint CRDs chart
        run: helm lint --strict helm/temporal-worker-controller-crds

  helm-template-crds:
    name: Template CRDs Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Template CRDs chart
        run: helm template test-release helm/temporal-worker-controller-crds

  helm-check-rbac:
    name: Check Helm RBAC wasn't manually updated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Regenerate and diff
        run: make manifests && git diff --exit-code helm/temporal-worker-controller/templates/rbac.yaml

  helm-validate-succeed:
    name: All Helm Validations Succeed
    needs:
      - helm-lint
      - helm-template
      - helm-lint-crds
      - helm-template-crds
      - helm-check-rbac
    runs-on: ubuntu-latest
    if: always()
    env:
      RESULTS: ${{ toJSON(needs.*.result) }}
    steps:
      - name: Check results
        run: |
          if [[ -n $(echo "$RESULTS" | jq '.[] | select (. != "success")') ]]; then
            exit 1
          fi
