name: publish-main-image

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  publish-main-image:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: ./.github/actions/setup-go
        with:
          fetch-depth: '0'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: ./.github/actions/docker-login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --config .goreleaser.main.yml --snapshot --clean

      - name: Push snapshot images
        run: |
          docker push "temporalio/temporal-worker-controller:main-amd64"
          docker push "temporalio/temporal-worker-controller:main-arm64"
      
      - name: Create and push manifest for :main tag
        run: |
          docker manifest create "temporalio/temporal-worker-controller:main" "temporalio/temporal-worker-controller:main-amd64" "temporalio/temporal-worker-controller:main-arm64"
          docker manifest push "temporalio/temporal-worker-controller:main"
